name: Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Log in to Docker registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Generate image name
        id: reponame
        uses: ashley-taylor/regex-property-action@v1.3
        with:
          value: ${{ github.repository }}
          regex: /|-|_
          flags: g
          replacement: _

      - name: Show image name
        run: echo "${{ steps.reponame.outputs.value }}"

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: DOCKERFILE
          push: false
          tags: ${{ secrets.REGISTRY_HOST }}/${{ steps.reponame.outputs.value }}:latest, ${{ secrets.REGISTRY_HOST }}/${{ steps.reponame.outputs.value }}:${{ github.run_number }}

      - name: Push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: DOCKERFILE
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ steps.reponame.outputs.value }}:latest, ${{ secrets.REGISTRY_HOST }}/${{ steps.reponame.outputs.value }}:${{ github.run_number }}

      - name: Delete old Docker images
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASS }}
          REPOSITORY: ${{ steps.reponame.outputs.value }}
        run: |
          chmod +x ./_scripts/delete_old_docker_images.sh
          ./_scripts/delete_old_docker_images.sh $REGISTRY_USER $REGISTRY_PASSWORD $REGISTRY_HOST $REPOSITORY
